version: '2'

services:

  # 使用 SSH TUNNEL 创建 SOCKS5 代理( SOCKS5 协议 )
  ssh-tunnel-socks5-server:
    image: jnovack/autossh
    container_name: ssh-tunnel-socks5-server
    entrypoint:
      autossh
      -M 0
      -N
      -o ServerAliveInterval=5
      -o ServerAliveCountMax=1
      -o "ExitOnForwardFailure yes"
      -o "StrictHostKeyChecking no"
      -t -t
      -i /id_rsa
      -D 0.0.0.0:1080
      -p $SSH_HOSTPORT
      $SSH_HOSTUSER@$SSH_HOSTNAME
    ports:
    - "$SSH_TUNNEL_SOCKS5_PORT:1080"
    restart: always
    volumes:
    - ~/.ssh/id_rsa:/id_rsa

  # 使用gost代理SOCKS5端口( HTTP 协议 )
  gost-server:
    image: ginuerzh/gost
    container_name: gost-server
    command: -L=:8080 -F=socks5://ssh-tunnel-socks5-server:1080
    ports:
    - "$GOST_PORT:8080"
    restart: always
    depends_on:
    - ssh-tunnel-socks5-server

  # 使用privoxy代理SOCKS5端口( HTTP 协议 )
  privoxy:
    image: rdsubhas/tor-privoxy-alpine
    container_name: privoxy
    entrypoint: sh -c 'echo "listen-address 0.0.0.0:8118" > /etc/service/privoxy/config && echo "forward-socks5 / ssh-tunnel-socks5-server:1080 ." >> /etc/service/privoxy/config && privoxy --no-daemon /etc/service/privoxy/config'
    ports:
    - "$PRIVOXY_PORT:8118"
    restart: always
    depends_on:
    - ssh-tunnel-socks5-server